= 程序员，你为什么需要一台mac?
:published_at: 2015-03-30


> 用了mac ,我再也回不去了。

A:帅哥，我电脑坏了。 B:重装系统吧，包好！ 
重装系统 windows系统解决所有系统问题的一剂神药。Mac 时代再也不需要做这种老命伤财的事情了,没有什么工具比一个稳定可靠，可以持续运行的操作系统更好了。
It was the best of times, it was the worst of times.
站在风口浪尖的，经历着这最美好和最糟糕时代的程序员们，带上你最好的兵器，出去战斗吧。

## 颜值和逼格
> 苹果笔记本一直都卓尔不群，崇尚着一种充满艺术化的感觉，而且苹果钟爱白色，就如同纯净净白的雪一样，结合了被咬了一口的苹果LOGO，显得苹果就是与众不同。

想象一下，温柔的午后，你坐在放着音乐的咖啡厅，盯着黑色编辑器的屏幕，手指在键盘游走。逼格真不是你刻意营造的。或者，你拿着mac在路上行走，程序员的自豪高也会不知不觉的迸发出来。

## 超级强大的OS
* 纯净的工作模式
windows 的世界，所有的软件都占用着同一个界面，臃肿，难管理，很闹心。
Mac OS可以配置多个桌面，不同的桌面可以开启不同的任务，每个任务又可以互不干扰。可以让你完全沉浸自己的编码世界，不用担心任何打扰。不同任务的切换，也在手指轻移中完成，就是这样丝滑。

* 随时随地待命
你可以以最快速的地进入战斗状态。就算重启，mac 也能在启动后，恢复到你关机时的工作状态。无需任何操作。这一点真是非常贴心呀。盖上盖子，系统就自动待机了，简单干脆。
* unix
Mac OS X是真正的Unix（符合标准，有授权，合法的可以用Unix商标）。大多数这类开发，你可以在Mac OS X下做，在Linux下执行。
Mac OS X是一个非常好的平衡，Unix式的命令行、脚本能力它全部具备，而且带有一个非常好用高效的GUI。所以不管你是CLI（命令行界面）控，还是GUI控，你都应该可以玩的很好。
基于苹果的封闭式授权，mac 几乎不需要杀毒软件。怎么玩都不会侧漏。

* 快捷方便
可以使用十个小时的电池，不用手动清理内存，retina屏幕，各种贴心的软件和服务。对于一个这样的操作系统，我还有什么奢求呢。

## 跨平台
移动互联网的发展，大家使用电脑的时间变得更短了。对于电脑的使用，我们越来越集中在浏览器和即时通讯。我们很少再需要打开很多其他应用，作为一个普通使用者。浏览器和QQ等聊天工具，足够我们的日常使用。这些应用早就没有操作系统的限制了。
* 开发语言
作为开发者，大多数主流的开发语言是没有操作系统限制的。厂商都推出了跨平台的类库支持。 
* 编辑器
对于必不可少的是代码编辑器，常用的编辑器至少是跨平台的。像Intellij 公司的所有产品，webstrom 、phpstrom等等






